# Hi there!
# These are the settings for Selfstarter.
# This is more tidy than changing the HTML if all you want to do is rename things and swap out images

# You should totally change the HTML and CSS though
# Checkout app/assets/stylesheets/variables.css.scss to change around the CSS quickly

# Set your project goal here - dollar amount
# NOTE: if you manually want to adjust your progress to test the site, head over to the Order model (app/models/order.rb)
project_goal: 25000

# If you want to edit the FAQ, head over to app/views/preorder/homepage/_faqs.html.erb

# For other product_name usage
product_name: "Advlo"

# This'll be both the page header (top nav)
product_name_header: "Advlo"

# This'll be both the page title (<title></title>) and the name in the header
product_name_title: "Advlo - Adventure Local"

# This will be used in sentences like Hooray You've just reserved product_description
product_description: "Adventure Local"

# An image showcasing your product -- it'll show up when you pin your product
# It should be in app/assets/images
product_image_path: "advlo_video_pin.png"

# The message on the preorder page, Lockitron's is ""
value_proposition: "Advlo needs your help...so its time to get Adventurous"

# YouTube or Vimeo Video URL (The embed URL, without the query string options)
# Replace /embed/ in your video url path with /v/ for video playback to work.
video_embed_url: "//player.vimeo.com/video/33035011?title=0&amp;byline=0&amp;portrait=0&amp;color=ff0179"

# If set to true, then the image at "/assets/video_placeholder.png" will be shown in place of the youtube
# video.  When the user clicks it, the vid will replace the image and start playing.
#
# NOTE: you can set this to false, and no image will be use - first frame of the video will be displayed
#
# NOTE: this only works for youtube video at the moment.  If its not for youtube, then just leave this property blank
use_video_placeholder: 

# Amazon settings -- you'll need an Amazon Payments account, sign up here --> http://bit.ly/SGksTv

# To find your access key and secret key, head over to here --> http://bit.ly/R4I4ky (Follow that guide in the Seller Central page)
amazon_access_key: "AKIAJHXXG3V2FXBMPFYA"
amazon_secret_key: "uYXxuAMcnKODnrR1o8fBYGELk6pCcXuT61DI7po2"
#price: 	19.95

# if use_payment_options is set to true, then a set of radio buttons will be displayed with various payment options.
# There is a PaymentOption model for storing info about payment options.  To set up your payment options you should
# put code in seeds.rb, then run rake db:seed
use_payment_options: true

#What ppl see on amazon checkout
payment_description: "Thank you for being an Advlo backer! We can't do this without you"

# Amazon limits how much we can charge people with their Multi-Use tokens.
# You probably should add some leeway to account for international shipping
# this value will be added to the price to create a charge limit
charge_limit: 20.00

# Stats settings

# On Lockitron, it's "backers"
primary_stat: "adventurers"
# This'll show up in the tweet as, "I'm backer number ..."
primary_stat_verb: 'adventurer'

# The 2nd call to action button, towards the middle-ish of the page
middle_reserve_text: "Get Updates ..."

# When the project should end
#expiration_date: <%= DateTime.now + 29 %>

# Text to show inside the progress bar, when the goal reaches/exceeds 100%
progress_text: "Funding Goal Reached!"

# Call to action section

# On Lockitron, it's "First Batch Ships in March 2013"
ships: "Coming Spring 2015"

# On Lockitron, it's "Reserve Now"
call_to_action: "SUPPORT ADVLO"
# On Lockitron, this is "Only $149 for a limited time"
price_human: "It costs money!"

# The paragraph below the price. You'd probably say something about how you're not going to charge them before it ships (so it's less risky).
dont_give_them_a_reason_to_say_no: "You'll get this exact site. All you'll need to get started is a great product."

# Social Stuff
facebook_app_id: "210802829129036"
# Tweets are prefixed with "I'm #{Settings.primary_stat} number X for #{Settings.product_name}"
# Maybe mention something about your product vision -- e.g. "to replace keys with my phone"
tweet_text: "to crowdfund"

# Google Analytics
google_id: "1234567890"

# FB share link
#fb_share_link: "";

# If you want to change the images for the key points (e.g. "Kickstarter is not a store")
# They're in app/assets/images/#{pointer_number}-background.png
# So, the first key point, it's at app/assets/images/1-background.png
# Alternatively, change it up in app/assets/stylesheets/homepage/key_points.css.scss
